### ISSUE TITLE
Update BOM Cost message 

### ISSUE THREAD

**Issue by yadavyk** [frappe/erpnext_ui_tests#113]
Problem : The update BOM cost button's functioning is quite vague. Even if there are no changes made in the costing of the BOM, the toast still says "Cost updated". In case of no actual cost changes, the toast could be improved to say something like "No changes". 

Actual : 

![actual](https://user-images.githubusercontent.com/32797974/171809763-ecf20c64-6d9a-4cd3-a352-0698c8e26f97.png)

Expected : 

![Untitled 1](https://user-images.githubusercontent.com/32797974/171809805-611b3c8e-d5fd-4e44-a535-a5f4c0080339.png)

**Comment by nidhipurohit11** [comment]
![image](https://user-images.githubusercontent.com/82337328/194289170-e2debf15-ca7f-46df-8fdb-18d6d015c1a2.png)
