### ISSUE TITLE
Inventory tab hides on hitting "maintain stock"checkbox 

### ISSUE THREAD

**Issue by yadavyk** [frappe/erpnext_ui_tests#135]
**Use case :** While creating template item, the "maintain stock" checkbox has to be unchecked so that item variants can be created. However upon checking "maintain stock" , the inventory tab hides. GIF for reference : 

![inventory_tab](https://user-images.githubusercontent.com/32797974/173787228-9ded1078-2379-4d58-be4b-b73f2b1a5ea3.gif)

[This ](https://github.com/frappe/erpnext/pull/31284)breaks cases like : https://github.com/erpnext/erpnext_ui_tests/pull/62

**Comment by ankush** [comment]
@yadavyk should be fixed after https://github.com/frappe/erpnext/pull/31354 ?

**Comment by yadavyk** [comment]
@ankush , yup fixed. Closing this
