### ISSUE TITLE
Link doctype error 

### ISSUE THREAD

**Issue by yadavyk** [frappe/erpnext_ui_tests#138]
**Issue :** Upon trying to link a document in address or contact doctype, a server error is thrown 

**Steps to reproduce :** 

1. Create a customer 
2. Go to Address / Contact Doctype 
3. Under Reference section, select a link doctype such as Customer 

**Screenshot :** 

![customer address link error ](https://user-images.githubusercontent.com/32797974/173884901-19f4d935-b42c-43fa-b610-0aa4fb7f680a.png)

Breaks [this](https://github.com/erpnext/erpnext_ui_tests/pull/97) & [this](https://github.com/erpnext/erpnext_ui_tests/pull/110)

**Comment by ankush** [comment]
fixed via https://github.com/frappe/frappe/pull/17230 

---

@yadavyk open such issue in frappe/frappe repo. This is not a issue for UI test but a bug in framework.
